### ISSUE TITLE
hello, this is not an issue but is it possible to create this also for iOS?

### ISSUE THREAD

**Issue by ahmdsdk** [thebylito/react-native-scratch-card#3]

**Comment by thebylito** [comment]
It's not impossible, but unfortunately I do not have the expertise to do that. We will be waiting for a PR for this feature.

**Comment by ahmdsdk** [comment]
Hopefully, when I get better with Objective-C and iOS I will create a PR for that :).. for now I have found another library "react-native-scratch-view" maybe I can try to integrate it into this one.
