### ISSUE TITLE
Not working for me 

### ISSUE THREAD

**Issue by nileshmean** [thebylito/react-native-scratch-card#4]
Its not working with latest react native and 
> Task :app:processDebugManifest FAILED
/var/DemoLearn/test/android/app/src/debug/AndroidManifest.xml:11:7-34 Error:
        Attribute application@allowBackup value=(false) from AndroidManifest.xml:11:7-34
        is also present at [com.clock.scratch:Scratch:1.0.0] AndroidManifest.xml:12:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:7:5-117 to override.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:11:7-34
        is also present at [com.clock.scratch:Scratch:1.0.0] AndroidManifest.xml:12:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:7:5-117 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by thebylito** [comment]
Hi, can you try the new version?

yarn add react-native-scratch-card@1.1.0

**Comment by ranjitpradhan87** [comment]
Thank you, it is working now.

**Comment by ghost** [comment]
I have installed react-native-scratch-card@1.1.0 but it is showing 


Execution failed for task ':app:preDebugBuild'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.clock.scratch:Scratch:1.0.0.
     Required by:
         project :app > project :react-native-scratch-card

**Comment by ranjitpradhan87** [comment]
Please follow the process like it is showing here 

https://github.com/thebylito/react-native-scratch-card#1---install-the-package
